-- schema_ensaio_001.sql
CREATE TABLE IF NOT EXISTS Tbl_Ensaio_001 (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    id_projeto INTEGER,
    id_procedimento INTEGER,
    Rodovia TEXT,
    Trecho TEXT,
    Sub_trecho TEXT,
    Protocolo INTEGER,
    Hora TEXT,
    Projeto TEXT,
    Material TEXT,
    Usina TEXT,
    Local TEXT,
    Data_rec TEXT,
    Data_ensaio TEXT,
    Placa TEXT,
    Procedimento TEXT,
    Obra TEXT,
    Clima TEXT,
    Operador TEXT,
    Tipo_ext TEXT,
    Temp REAL,
    Am_ligante REAL,
    Am_Lavada REAL,
    Fator_correção REAL,
    Teor REAL,
    Filler REAL,
    -- Retenção e Percentuais de Peneiras
    Ret_Pen01 REAL, Ret_Pen02 REAL, Ret_Pen03 REAL, Ret_Pen04 REAL, Ret_Pen05 REAL,
    Ret_Pen06 REAL, Ret_Pen07 REAL, Ret_Pen08 REAL, Ret_Pen09 REAL, Ret_Pen10 REAL,
    Ret_Pen11 REAL, Ret_Pen12 REAL, Ret_Pen13 REAL, Ret_Pen14 REAL, Ret_Pen15 REAL,
    Ret_Pen16 REAL, Ret_Pen17 REAL, Ret_Pen18 REAL, Ret_Pen19 REAL, Ret_Pen20 REAL,
    Perc_Pen01 REAL, Perc_Pen02 REAL, Perc_Pen03 REAL, Perc_Pen04 REAL, Perc_Pen05 REAL,
    Perc_Pen06 REAL, Perc_Pen07 REAL, Perc_Pen08 REAL, Perc_Pen09 REAL, Perc_Pen10 REAL,
    Perc_Pen11 REAL, Perc_Pen12 REAL, Perc_Pen13 REAL, Perc_Pen14 REAL, Perc_Pen15 REAL,
    Perc_Pen16 REAL, Perc_Pen17 REAL, Perc_Pen18 REAL, Perc_Pen19 REAL, Perc_Pen20 REAL,
    -- Ensaio Rice
    Rice_1 REAL, Rice_2 REAL, Rice_3 REAL, Dens_Rice REAL,
    -- Umidade e Cálculos
    Umid_1 REAL, Umid_2 REAL, Teor_real REAL,
    CpAr_1 REAL, CpAr_2 REAL, CpAr_3 REAL,
    CpIm_1 REAL, CpIm_2 REAL, CpIm_3 REAL,
    CpSa_1 REAL, CpSa_2 REAL, CpSa_3 REAL,
    Dens_Apar REAL, Vazios REAL, VCB REAL, VAM REAL, RBV REAL,
    -- Resistência e Fluência
    Alt_Cp1 REAL, Alt_Cp2 REAL, Alt_Cp3 REAL,
    Con_Prensa REAL,
    RT_Cp1 INTEGER, RT_Cp2 INTEGER, RT_Cp3 INTEGER, RTCD REAL,
    Est_Cp1 INTEGER, Est_Cp2 INTEGER, Est_Cp3 INTEGER, Estabilidade REAL,
    Fl_Cp1 REAL, Fl_Cp2 REAL, Fl_Cp3 REAL, Fl_Cp4 REAL, Fl_Cp5 REAL, Fl_Cp6 REAL, Fluencia REAL,
    Ass_1 TEXT, Ass_2 TEXT,
    FOREIGN KEY (id_projeto) REFERENCES Tbl_Projeto(id),
    FOREIGN KEY (id_procedimento) REFERENCES Tbl_Procedim(id)
);
